 version: "3.7"

 services:
   app1:
     ports:
       - 5000:8000
     build: .
     image: sbeltran2006/laravel-crud-app
     volumes:
      - .:/app/
     networks:
      customnetwork:
        ipv4_address: 172.20.0.10

   dba:
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
        MYSQL_DATABASE: laravel_db
        MYSQL_USER: MYSQL_USER
        MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
        - "9906:3306"
    volumes:
      - ./laravel_db.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - customnetwork


 networks:
  customnetwork:
    ipam:
      config:
        - subnet: 172.20.0.0/16

