version: '3.7'
services:
  app:
    build:
      context: ./
    volumes:
      - ./app/public :/var/www/html
    ports:
      - "5000:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
